server:
  port: 7003

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
      
spring:
  application:
    name: ORDER-SERVICE
    
management:
  endpoints:
    web:
      exposure:
        include: "*"